# Generated by Django 3.2.2 on 2021-05-17 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inbox',
            fields=[
                ('TaskId', models.AutoField(primary_key=True, serialize=False)),
                ('inboxTaskName', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='PlanningPeriod',
            fields=[
                ('planningPeriodId', models.AutoField(primary_key=True, serialize=False)),
                ('scheduledPlanning', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('projectId', models.AutoField(primary_key=True, serialize=False)),
                ('projectName', models.CharField(max_length=500)),
                ('completedCheck', models.BinaryField()),
            ],
        ),
        migrations.CreateModel(
            name='ProjectTask',
            fields=[
                ('TaskId', models.AutoField(primary_key=True, serialize=False)),
                ('taskName', models.CharField(max_length=500)),
                ('projectName', models.CharField(max_length=500)),
                ('todoCheck', models.BinaryField()),
                ('completedCheck', models.BinaryField()),
                ('addedDate', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='SimpleTask',
            fields=[
                ('TaskId', models.AutoField(primary_key=True, serialize=False)),
                ('taskName', models.CharField(max_length=500)),
                ('todoCheck', models.BinaryField()),
                ('completedCheck', models.BinaryField()),
                ('addedDate', models.DateTimeField()),
            ],
        ),
    ]
